### ISSUE TITLE
Lego Skyline Kiel

### ISSUE THREAD

**Issue by x64toho** [TheZingo/musicbox#1]
Hey, 

i know this is a little unorthodox way of contacting you. But I saw your Skyline MOC on your website an hope there is a way you could provide me with the instructions?

**Comment by TheZingo** [comment]
@x64toho Hey, no problem. I've updated the [post ](https://ptmm.de/about/kiel-skyline/) to include building instructions and the bricklink XML part list. Furthermore, the info page now has a mail link to get in touch.
